### PR TITLE
Re: Fix plugins not being found when no node_modules exists

### LINKED ISSUE #170: Finding plugins breaks when the package manager doesn't use node_modules
When trying to use oclif with a package manager such as Yarn 2, the following error message occurs:

```
(node:621147) Error Plugin: @maintainer/package: could not find package.json with {
  type: 'core',
  root: '/path/to/project/root',
  name: '@oclif/plugin-help'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: @maintainer/package
root: /path/to/project/root
See more details with DEBUG=*
```

Digging into the code, it seems pretty obvious that this is because of the fact that this package looks for plugins in `node_modules`, but Yarn 2 doesn't use `node_modules`. 

As per the [Yarn 2 documentation](https://yarnpkg.com/features/pnp), this is somewhat easily solved with a change to utilize `resolve@>=1.9`. Any pitfalls or caveats existing contributors/maintainers can think of?

Yes, Yarn 2 is in RC stage but it will not be so eventually and this issue will need to be resolved. (Heh.)

I'm most probably going to try to fix this myself so I can obstinately use the new modules system, but tracking issues is important so I'm doing this first.

### PR DESCRIPTION
**Pull request by benatshippabo**
## Description
```
Fixes #170.

As I mentioned in the issue, Yarn 2 uses a different package system that does not have node_modules. As such, relying on node_modules should be discouraged.

Yarn suggests using the resolve package, and this is the approach I have taken.

Please let me know if any further changes are required. I tried to conform to idioms of the code, but for testing in particular I wasn't sure what the guidelines were.
```

## Technical Details

Uses native `require.resolve` to resolve dependency package's path instead of the third party `resolve` package. Addresses @mdonnalley's comment https://github.com/oclif/config/pull/171#issuecomment-982128689

### For Yarn 2+ zero install users who needed this issue resolved
- you may still have to use `yarn patch` to add `main: lib/index.js` inside the `package.json` of oclif plugins that still fail to resolve

## Context
#171

### CODE REVIEW

**Comment by benatshippabo** [comment]
I signed the CLA, but it seems that the CI check is still failing 🤷‍♂️ 
image

**Comment by mdonnalley** [comment]
@benatshippabo I tested this locally with [sfdx-cli](https://github.com/salesforcecli/sfdx-cli) and I'm still seeing the same issue:

```
~/repos/salesforcecli/sfdx-cli [main] : bin/run auth:list
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'link',
  root: '/Users/mdonnalley/repos/salesforcecli/plugin-auth',
  name: '@salesforce/plugin-auth',
  tag: undefined
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'dev',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@oclif/plugin-command-snapshot'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'dev',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-release-management'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@oclif/plugin-autocomplete'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@oclif/plugin-commands'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@oclif/plugin-help'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@oclif/plugin-not-found'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@oclif/plugin-plugins'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@oclif/plugin-update'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@oclif/plugin-warn-if-update-available'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@oclif/plugin-which'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-alias'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-apex'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-auth'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-config'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-custom-metadata'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-data'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-generator'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-limits'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-org'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-source'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-schema'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-telemetry'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-templates'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-trust'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/plugin-user'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: '@salesforce/sfdx-plugin-lwc-test'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
(node:90678) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'core',
  root: '/Users/mdonnalley/repos/salesforcecli/sfdx-cli',
  name: 'salesforce-alm'
}
module: @oclif/config@1.17.0
task: loadPlugins
plugin: sfdx-cli
root: /Users/mdonnalley/repos/salesforcecli/sfdx-cli
See more details with DEBUG=*
 ›   Error: command auth:list not found
```

**Comment by benatshippabo** [comment]
> @benatshippabo I tested this locally with [sfdx-cli](https://github.com/salesforcecli/sfdx-cli) and I'm still seeing the same issue:

Thanks for the prompt feedback @mdonnalley! I'm not sure how to test this against that repository, but I think I found the problem. Could you please re-test it? 🙏

**Comment by mdonnalley** [comment]
@benatshippabo I'm still seeing the same error with your latest changes.

You can test against sfdx-cli like this:

```
git clone git@github.com:salesforcecli/sfdx-cli.git
cd sfdx-cli
yarn link @oclif/config
bin/run config:list
```

Just make sure to compile your changes before running `bin/run config:list` again

**Comment by benatshippabo** [comment]
> @benatshippabo I'm still seeing the same error with your latest changes.
> 
> You can test against sfdx-cli like this:
> 
> ```
> git clone git@github.com:salesforcecli/sfdx-cli.git
> cd sfdx-cli
> yarn link @oclif/config
> bin/run config:list
> ```
> 
> Just make sure to compile your changes before running `bin/run config:list` again

Thanks for the test steps.

I just figured out the issue! The issue is that the `package.json` for those missing plugins do not specify the `main` field. Because it is missing that field in the `package.json`, the [node module resolution algorithm](https://nodejs.org/api/modules.html#all-together) will look at the root level for `index.js` (see `LOAD_AS_DIRECTORY(X)` step 2 and `LOAD_INDEX(X)`). We can test this by trying to use the node module resolution to try finding it in the node repl:

```bash
# at the root directory of sfdx
yarn
node -e "console.log(require.resolve('@oclif/parser'))"
node -e "console.log(require.resolve('@oclif/plugin-commands'))"
```

If we inspect each of those package's `package.json` we can see that the compiled `index.js` is put inside the `lib` folder, but from the example, only `@oclif/parser` specifies `main` and that is why `require.resolve` is able to find `@oclif/parser` and not `@oclif/plugin-commands`.

We can test the fix by adding `main: "lib/index.js"` inside `node_module/@oclif/plugin-commands/package.json` and then rerunning:

```bash
# we can see here that it will now resolve properly 😃
node -e "console.log(require.resolve('@oclif/plugin-commands'))"
```

I think this will require some minor updates to all the missing plugins so that is is compliant with the node module resolution algorithm.

<details>
<summary>List of plugins missing the `main` field in `package.json`</summary>

```
'@oclif/plugin-command-snapshot'
'@salesforce/plugin-release-management'
'@oclif/plugin-autocomplete'
'@oclif/plugin-update'
'@oclif/plugin-warn-if-update-available'
'@oclif/plugin-which'
'@salesforce/plugin-alias'
'@salesforce/plugin-apex'
'@salesforce/plugin-auth'
'@salesforce/plugin-config'
'@salesforce/plugin-custom-metadata'
'@salesforce/plugin-data'
'@salesforce/plugin-limits'
'@salesforce/plugin-org'
'@salesforce/plugin-source'
'@salesforce/plugin-schema'
'@salesforce/plugin-telemetry'
'@salesforce/plugin-templates'
'@salesforce/plugin-trust'
'@salesforce/plugin-user'
'@salesforce/sfdx-plugin-lwc-test'
'@oclif/plugin-warn-if-update-available'
```

</details>

This will probably require some effort to update these plugins. Thoughts @mdonnalley?

**Comment by mdonnalley** [comment]
@benatshippabo Good find!

Unfortunately, if we require that plugins must specify the `main` field then this would be a breaking change, which we're not willing to do on this package since it will soon be in maintenance mode.

Is it possible to fallback to the old behavior whenever a module isn't found?

**Comment by benatshippabo** [comment]
> @benatshippabo Good find!
> 
> Unfortunately, if we require that plugins must specify the `main` field then this would be a breaking change, which we're not willing to do on this package since it will soon be in maintenance mode.

That's unfortunate, maybe we can see this in the package that will supersede this one?

> Is it possible to fallback to the old behavior whenever a module isn't found?

Done! @mdonnalley I re-added the legacy dependency resolution function as a fallback
https://github.com/benatshippabo/oclif-config/blob/12f8d90adb6c2d2ff632d37a0c505cf5583d1290/src/plugin.ts#L129-L147

File: src/plugin.ts [hunk 1]
```diff
@@ -98,23 +98,35 @@ function topicsToArray(input: any, base?: string): Topic[] {
...
-async function findRoot(name: string | undefined, root: string) {
-  // essentially just "cd .."
-  function * up(from: string) {
-    while (path.dirname(from) !== from) {
-      yield from
-      from = path.dirname(from)
-    }
-    yield from
-  }
+async function findRootLegacy(name: string | undefined, root: string): Promise<string | undefined> {
```
Comment (benatshippabo) [inline src/plugin.ts:129]: > @benatshippabo Good find!
> 
> Unfortunately, if we require that plugins must specify the `main` field then this would be a breaking change, which we're not willing to do on this package since it will soon be in maintenance mode.

That's unfortunate, maybe we can see these changes once the package that will supersede this one is released?

> Is it possible to fallback to the old behavior whenever a module isn't found?

Done! @mdonnalley I re-added the legacy dependency resolution function as a fallback
https://github.com/benatshippabo/oclif-config/blob/12f8d90adb6c2d2ff632d37a0c505cf5583d1290/src/plugin.ts#L129-L147

**Comment by mdonnalley** [comment]
Thanks @benatshippabo 

Testing is going well so far. I'm going to test it out a bit more before merging though

[oclif/core](https://github.com/oclif/core) is the heir apparent to this project so it'd be great if you could port these changes over there as well. It should be a fairly straightforward copy and paste since most of this code is unchanged: https://github.com/oclif/core/blob/main/src/config/plugin.ts#L41

I would prefer to keep the legacy fallback to persevere backwards compatibility between plugins that use oclif/config and plugins that use oclif/core. However, I will add a note about adding the `main` field to the soon-to-be-published migration guide. That way we can drop the legacy code path if/when we do a major version bump of oclif/core

**Review by mdonnalley — APPROVED** [review]

**Comment by cromwellryan** [comment]
@benatshippabo - thanks so much for your thorough and thoughtful work on this PR. This [comment](https://github.com/oclif/config/pull/289#issuecomment-983904051) is amazing. 🙌

**Comment by benatshippabo** [comment]
> Thanks @benatshippabo
> 
> Testing is going well so far. I'm going to test it out a bit more before merging though

Awesome! Thanks for being so responsive for this pull request.

> [oclif/core](https://github.com/oclif/core) is the heir apparent to this project so it'd be great if you could port these changes over there as well. It should be a fairly straightforward copy and paste since most of this code is unchanged: https://github.com/oclif/core/blob/main/src/config/plugin.ts#L41
> 
> I would prefer to keep the legacy fallback to persevere backwards compatibility between plugins that use oclif/config and plugins that use oclif/core. However, I will add a note about adding the `main` field to the soon-to-be-published migration guide. That way we can drop the legacy code path if/when we do a major version bump of oclif/core

Done https://github.com/oclif/core/pull/309

**Comment by dylanpomeroy** [comment]
Hi @mdonnalley

**Comment by benatshippabo** [comment]
> @mdonnalley bump on the above ^^ any way we can get a tag version to use with this change?
> 
> Thanks!

The latest version `1.18.2` has this fix
